// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package injector

import (
	"github.com/google/wire"
	"github.com/norun9/postmantest/internal/api/handler"
	"github.com/norun9/postmantest/internal/api/infra/query"
	"github.com/norun9/postmantest/internal/api/usecase"
	"github.com/norun9/postmantest/pkg/config"
	"github.com/norun9/postmantest/pkg/db"
)

// Injectors from wire.go:

func InitializeRestHandler(http config.HTTP, mySQL config.MySQL) handler.RestHandler {
	sqlDB := db.NewMySQL(mySQL)
	client := db.NewDB(sqlDB)
	post := query.NewPost(client)
	usecasePost := usecase.NewPost(post)
	v := handler.GetRouteMap(usecasePost)
	restHandler := handler.NewRestHandler(v)
	return restHandler
}

func InitializeRouteMap(http config.HTTP, mySQL config.MySQL) map[handler.Path]handler.Route {
	sqlDB := db.NewMySQL(mySQL)
	client := db.NewDB(sqlDB)
	post := query.NewPost(client)
	usecasePost := usecase.NewPost(post)
	v := handler.GetRouteMap(usecasePost)
	return v
}

// wire.go:

var RouteMap = wire.NewSet(db.NewDB, db.NewMySQL, usecase.NewPost, query.NewPost)
