version: "3"

services:
  mysql:
    platform: linux/x86_64
    image: mysql:5.7-oracle
    command: ["mysqld", "--ssl=0"]
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: testdb
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      TZ: Asia/Tokyo
    ports:
      - 5306:3306
    volumes:
      - ./docker/db/config:/etc/mysql/conf.d
      - ./docker/db/initdb.d:/docker-entrypoint-initdb.d
  api:
    build:
      context: .
      dockerfile: ./docker/backend/api/Dockerfile
    ports:
      - "7070:3000"
    depends_on:
      - mysql
    volumes:
      - ./:/home
    command: /home/wait-for-it.sh db:5306 --timeout=30 --strict
    tty: true