version: "3"

services:
  go:
    container_name: go
    build:
      context: .
      dockerfile: ./docker/backend/api/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    tty: true
    networks:
      - go_network
  mysql:
    container_name: mysql
    platform: linux/x86_64
    image: mysql:5.7-oracle
    command: ["mysqld", "--ssl=0"]
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: testdb
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      TZ: Asia/Tokyo
    ports:
      - "3306:3306"
    volumes:
      - ./docker/db/config:/etc/mysql/conf.d
      - ./docker/db/initdb.d:/docker-entrypoint-initdb.d
    networks:
      - go_network
networks:
  go_network:
    external: true