env:
  name: "test"
test:
  http:
    port: 8080
    web_domain: localhost
    protcol: "http"
    cors:
      allowed_origins:
        - "*"
  mysql:
    db_host: mysql-container
    db_name: testdb
    db_user_name: test
    db_password: test
    db_port: 3306
    max_idle_conns: 10
    max_open_conns: 10
    conn_max_lifetime: 300s
